#!/usr/bin/env python3
import skilstak.colors as c
import random as r

answers = [
        'It is certain',
        'It is decidedly so',
        'Without a doubt',
        'Yes, definitely',
        'You may rely on it',
        'As I see it, yes',
        'Most likely',
        'Outlook good',
        'Yes',
        'Signs point to yes',
        'Reply hazy try again',
        'Ask again later',
        'Better not tell you now',
        'Cannot predict now',
        'Concentrate and ask again',
        "Don't count on it",
        'My reply is no',
        'My sources say no',
        'Outlook not so good',
        'Very doubtful'
]

eastereggs = [['kill', 'Well then!'],['love', 'Go away!'],['hi','Hello!']]

while True:
    easter = 0
    user = input(c.clear + c.red + 'What do you want?\n' + c.reset).strip().lower()
    for i in eastereggs:
        if i[0] in user:
            print(c.rc() + i[1] + c.reset)
            input()
            easter = 1
    if easter == 0:
        print(c.rc() + r.choice(answers) + c.reset)
        input()
