#!/usr/bin/env python3
import skilstak.colors as c
import random as r

die = []

die.append('''
         -------
        |       |
        |   .   |
        |       |
         -------
''')

die.append('''
         -------
        |   .   |
        |       |
        |   .   |
         -------
''')

die.append('''
         -------
        |   .   |
        |   .   |
        |   .   |
         -------
''')

die.append('''
         -------
        | .   . |
        |       |
        | .   . |
         -------
''')

die.append('''
         -------
        | .   . |
        |   .   |
        | .   . |
         -------
''')

die.append('''
         -------
        | .   . |
        | .   . |
        | .   . |
         -------
''')

while True:
    current_die_side = r.choice(die)
    input(c.clear + c.rc() + current_die_side + c.reset)
